// import './spec/polyfill.spec.js'
// import './spec/fetch.spec.js'
// import './spec/get.spec.js'
// import './spec/head.spec.js'
// import './spec/delete.spec.js'
// import './spec/put.spec.js'
import './spec/post.spec.js'
// import './spec/patch.spec.js'
// import './spec/middleware.spec.js'
