// import './polyfill.spec.js'
// import './fetch.spec.js'
// import './get.spec.js'
// import './head.spec.js'
// import './delete.spec.js'
// import './put.spec.js'
import './post.spec.js'
// import './patch.spec.js'
// import './middleware.spec.js'
